### ISSUE TITLE
java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by Abdalqader27** [zoho/zdesk-asap-flutter#1]
after i installed [zohodesk_portal_services | Flutter Package](https://pub.dev/packages/zohodesk_portal_services)
`zohodesk_portal_services: ^1.0.1
`

then i initiated  the sdk 
`  ZohodeskPortalApikit.initializeSDK(orgId, appId, dc);
`

then 
`ZohodeskPortalKb.show();
`

then I got this error !!

FATAL EXCEPTION: main
E/AndroidRuntime(21149): Process: com.zoho_example.zoho_example, PID: 21149
E/AndroidRuntime(21149): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zoho_example.zoho_example/com.zoho.desk.asap.common.activities.ZDPBaseActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(21149): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime(21149): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime(21149): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(21149): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(21149): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(21149): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime(21149): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21149): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(21149): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(21149): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(21149): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21149): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(21149): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(21149): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(21149): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/AndroidRuntime(21149): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/AndroidRuntime(21149): 	at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:556)
E/AndroidRuntime(21149): 	at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:543)
E/AndroidRuntime(21149): 	at androidx.appcompat.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:163)
E/AndroidRuntime(21149): 	at com.zoho.desk.asap.common.activities.ZDPBaseActivity.onCreate(Unknown Source:19)
E/AndroidRuntime(21149): 	at android.app.Activity.performCreate(Activity.java:8595)
E/AndroidRuntime(21149): 	at android.app.Activity.performCreate(Activity.java:8573)
E/AndroidRuntime(21149): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/AndroidRuntime(21149): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
E/AndroidRuntime(21149): 	... 12 more
I/Process (21149): Sending signal. PID: 21149 SIG: 9

**Comment by vignesthillai** [comment]
@Abdalqader27  Please reach us out with support@zohodesk.com with issue's details. We shall track the case there.
